language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-lowest"'

install:
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - composer test --quiet
